class CreateQs < ActiveRecord::Migration[6.0]
  def change
    create_table :qs do |t|
      t.string :title, null: false
      t.string :content_1
      t.string :content_2
      t.string :content_3
      t.string :content_4
      t.string :content_5
      t.string :content_6
      t.string :content_7
      t.string :content_8
      t.string :content_9
      t.string :content_10
      t.string :content_11
      t.string :content_12
      t.string :content_13
      t.string :content_14
      t.string :content_15
      t.string :content_16
      t.string :content_17
      t.string :content_18
      t.string :content_19
      t.string :content_20
      t.string :content_21
      t.string :content_22
      t.string :content_23
      t.string :content_24
      t.string :content_25
      t.string :content_26
      t.string :content_27
      t.string :content_28
      t.string :content_29
      t.string :content_30
      t.string :content_31
      t.string :content_32
      t.string :content_33
      t.string :content_34
      t.string :content_35
      t.string :content_36
      t.string :content_37
      t.string :content_38
      t.string :content_39
      t.string :content_40
      t.string :content_41
      t.string :content_42
      t.string :content_43
      t.string :content_44
      t.string :content_45
      t.string :content_46
      t.string :content_47
      t.string :content_48
      t.string :content_49
      t.string :content_50
      t.string :content_51
      t.string :content_52
      t.string :content_53
      t.string :content_54
      t.string :content_55
      t.string :content_56
      t.string :content_57
      t.string :content_58
      t.string :content_59
      t.string :content_60
      t.string :content_61
      t.string :content_62
      t.string :content_63
      t.string :content_64
      t.string :content_65
      t.string :content_66
      t.string :content_67
      t.string :content_68
      t.string :content_69
      t.string :content_70
      t.string :content_71
      t.string :content_72
      t.string :content_73
      t.string :content_74
      t.string :content_75
      t.string :content_76
      t.string :content_77
      t.string :content_78
      t.string :content_79
      t.string :content_80
      t.string :content_81
      t.string :content_82
      t.string :content_83
      t.string :content_84
      t.string :content_85
      t.string :content_86
      t.string :content_87
      t.string :content_88
      t.string :content_89
      t.string :content_90
      t.string :content_91
      t.string :content_92
      t.string :content_93
      t.string :content_94
      t.string :content_95
      t.string :content_96
      t.string :content_97
      t.string :content_98
      t.string :content_99
      t.string :content_100
      t.references :user, null: false, foreign_key: true

      t.timestamps
    end
  end
end
